[package]
name = "trie_rs"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[lints]
workspace = true

[features]
test_utils = []

[dependencies]
lending-iterator.workspace = true
libc.workspace = true
memchr.workspace = true
wildcard.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[dev-dependencies]
insta.workspace = true
proptest = { workspace = true, features = ["std"] }
proptest-derive.workspace = true
trie_rs = { workspace = true, features = ["test_utils"] }
fs-err.workspace = true
