[package]
name = "numeric_range_tree_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[dependencies]
ffi.workspace = true
hll.workspace = true
inverted_index.workspace = true
inverted_index_ffi = { path = "../inverted_index_ffi" }
numeric_range_tree.workspace = true
workspace_hack.workspace = true
