[package]
name = "hll"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
fnv.workspace = true

[dev-dependencies]
hyperloglogplus = "0.4"

[lints]
workspace = true
