[package]
name = "hll"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fnv = { workspace = true }
hash32 = "0.3"
thiserror = { workspace = true }
workspace_hack.workspace = true
xxhash-rust = { version = "0.8", features = ["xxh32"] }
ahash = "0.8"
fxhash = "0.2"
wyhash = "0.5"

[dev-dependencies]
criterion.workspace = true
proptest = { workspace = true, features = ["std"] }

[[bench]]
name = "hll_operations"
harness = false
