[package]
name = "hll"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
fnv = { workspace = true }
hash32 = "1"
thiserror = { workspace = true }
workspace_hack.workspace = true

[dev-dependencies]
ahash = "0.8"
criterion.workspace = true
fxhash = "0.2"
proptest = { workspace = true, features = ["std"] }
wyhash = "0.5"
xxhash-rust = { version = "0.8", features = ["xxh32"] }

[[bench]]
name = "hll_operations"
harness = false
