site_name: RediSearch Documentation
site_url: http://redisearch.io
canonical_url: http://redisearch.io
repo_url: https://github.com/RedisLabsModules/RediSearch
theme: material


google_analytics:
  - 'UA-89573912-1'
  - 'auto'
markdown_extensions:
  - codehilite
  - toc(permalink=true)
  - admonition
  
extra:
  palette:
    primary: 'indigo'
    
  feature:
    tabs: false
pages:
    - 'Home': 'index.md'
    - 'Quick Start': 'Quick_Start.md'
    - 'Client Libraries': 'Clients.md'
    - 'Commands': 'Commands.md'       
    - 'Query Syntax': 'Query_Syntax.md'
    - 'Sortable Values': 'Sorting.md'
    - 'Extension API': Extensions.md
    - 'Stemming Support': Stemming.md
    - 'Python API': python_client.md
    - 'Java API': java_client.md
    - 'Document Payloads': payloads.md
    - Articles:
      - 'Multi-Threading in RediSearch': Threading.md
    

#google_analytics: ['UA-89573912-1', 'redisearch']