[package]
name = "rlookup_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ffi.workspace = true
c_ffi_utils.workspace = true
libc.workspace = true
rlookup.workspace = true
sorting_vector.workspace = true
value = { workspace = true, features = ["c_ffi_impl"] }
workspace_hack.workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }
