[package]
name = "rlookup_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
unittest = []

[dependencies]
rlookup.workspace = true
ffi.workspace = true
value = { workspace = true, features = ["c_ffi_impl"] }
libc.workspace = true
workspace_hack.workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[dev-dependencies]
rlookup_ffi = { path = ".", features = ["unittest"] }
redisearch_rs = { workspace = true, features = ["mock_allocator"] }
redis_mock.workspace = true
