[package]
name = "query_error"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils.workspace = true
strum.workspace = true

[lints]
workspace = true
