[package]
name = "query_error"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils.workspace = true
strum.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[lints]
workspace = true
