[package]
name = "tracing_redismodule_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
tracing_redismodule.workspace = true
ffi.workspace = true

[build-dependencies]
cbindgen.workspace = true

[lints]
workspace = true
