[package]
name = "build_utils"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
cbindgen.workspace = true
bindgen.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[lints]
workspace = true
