[package]
name = "sorting_vector"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
icu_casemap.workspace = true
thiserror.workspace = true
value = { workspace = true, features = ["c_ffi_impl"] }
workspace_hack.workspace = true

[dev-dependencies]
value = { workspace = true, features = ["test_utils"] }

[lints]
workspace = true
