[package]
name = "sorting_vector"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
icu_casemap.workspace = true
value = { workspace = true, features = ["c_ffi_impl"] }
workspace_hack.workspace = true

[dev-dependencies]
value.workspace = true

# Crate required to invoke C symbols
sorting_vector = { path = ".", features = ["unittest"] }
redisearch_rs = { path = "../c_entrypoint/redisearch_rs", features = ["mock_allocator"] }
redis_mock.workspace = true

[build-dependencies]
build_utils.workspace = true

[features]
unittest = []

[lints]
workspace = true
