# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under both the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree and the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree.

# Copied from fbsource fixup.

buildscript.run = false

# Generate a C/C++ build rule for all the C code

# [['cfg(all(target_arch = "x86_64", target_os = "linux"))'.cxx_library]]
# name = "ring-c-asm-elf-x86_84"
# srcs = [ "crypto/**/*.c", "pregenerated/*x86_64*-elf.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]

# # redundant `any` is needed to differentiate key for config specific to v0.17.5 version
# ['cfg(any(all(target_arch = "x86_64", target_os = "linux")))']
# version = "=0.17.5"
# ['cfg(any(all(target_arch = "x86_64", target_os = "linux")))'.env]
# RING_CORE_PREFIX = "ring_core_0_17_5_"
# [['cfg(any(all(target_arch = "x86_64", target_os = "linux")))'.cxx_library]]
# name = "ring-c-asm-elf-x86_84"
# srcs = [ "crypto/**/*.c", "pregenerated/*x86_64*-elf.S", "third_party/fiat/asm/fiat_curve25519_adx_mul.S", "third_party/fiat/asm/fiat_curve25519_adx_square.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]
# fixup_include_paths = ["include"]

# [['cfg(all(target_arch = "aarch64", target_os = "linux"))'.cxx_library]]
# name = "ring-c-asm-elf-aarch64"
# srcs = [ "crypto/**/*.c", "pregenerated/*armv8*-linux64.S", "pregenerated/*armx*-linux64.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# exclude = [ "crypto/cpu-intel.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]

# ['cfg(any(all(target_arch = "aarch64", target_os = "linux")))']
# version = "=0.17.5"
# ['cfg(any(all(target_arch = "aarch64", target_os = "linux")))'.env]
# RING_CORE_PREFIX = "ring_core_0_17_5_"
# [['cfg(any(all(target_arch = "aarch64", target_os = "linux")))'.cxx_library]]
# name = "ring-c-asm-elf-aarch64"
# srcs = [ "crypto/**/*.c", "pregenerated/*armv8*-linux64.S", "pregenerated/*armx*-linux64.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# exclude = [ "crypto/cpu-intel.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]
# fixup_include_paths = ["include"]

# [['cfg(all(target_arch = "x86_64", target_os = "macos"))'.cxx_library]]
# name = "ring-c-asm-macos-x86_64"
# srcs = [ "crypto/**/*.c", "pregenerated/*x86_64*-macosx.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]

# ['cfg(any(all(target_arch = "x86_64", target_os = "macos")))']
# version = "=0.17.5"
# ['cfg(any(all(target_arch = "x86_64", target_os = "macos")))'.env]
# RING_CORE_PREFIX = "ring_core_0_17_5_"
# [['cfg(any(all(target_arch = "x86_64", target_os = "macos")))'.cxx_library]]
# name = "ring-c-asm-macos-x86_64"
# srcs = [ "crypto/**/*.c", "pregenerated/*x86_64*-macosx.S", "third_party/fiat/asm/fiat_curve25519_adx_mul.S", "third_party/fiat/asm/fiat_curve25519_adx_square.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]
# fixup_include_paths = ["include"]

# [['cfg(all(target_arch = "aarch64", target_os = "macos"))'.cxx_library]]
# name = "ring-c-asm-macos-arm64"
# srcs = [ "crypto/**/*.c", "pregenerated/*armv8*-ios64.S", "pregenerated/*armx*-ios64.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# exclude = [ "crypto/cpu-intel.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]

# ['cfg(any(all(target_arch = "aarch64", target_os = "macos")))']
# version = "=0.17.5"
# ['cfg(any(all(target_arch = "aarch64", target_os = "macos")))'.env]
# RING_CORE_PREFIX = "ring_core_0_17_5_"
# [['cfg(any(all(target_arch = "aarch64", target_os = "macos")))'.cxx_library]]
# name = "ring-c-asm-macos-arm64"
# srcs = [ "crypto/**/*.c", "pregenerated/*armv8*-ios64.S", "pregenerated/*armx*-ios64.S" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# exclude = [ "crypto/cpu-intel.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]
# fixup_include_paths = ["include"]

# [['cfg(all(target_arch = "x86_64", target_os = "windows", target_env = "gnu"))'.cxx_library]]
# name = "ring-c-win-x86_84"
# srcs = [ "crypto/**/*.c" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]

# ['cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "gnu")))']
# version = "=0.17.5"
# ['cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "gnu")))'.env]
# RING_CORE_PREFIX = "ring_core_0_17_5_"
# [['cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "gnu")))'.cxx_library]]
# name = "ring-c-win-x86_84"
# srcs = [ "crypto/**/*.c" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# compiler_flags = ["-Wno-error"]
# fixup_include_paths = ["include"]

# [['cfg(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc"))'.cxx_library]]
# name = "ring-c-win-msvc-x86_84"
# srcs = [ "crypto/**/*.c" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]

# ['cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc")))']
# version = "=0.17.5"
# ['cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc")))'.env]
# RING_CORE_PREFIX = "ring_core_0_17_5_"
# [['cfg(any(all(target_arch = "x86_64", target_os = "windows", target_env = "msvc")))'.cxx_library]]
# name = "ring-c-win-msvc-x86_84"
# srcs = [ "crypto/**/*.c" ]
# headers = [ "include/**/*.h", "crypto/**/*.h", "third_party/**/*.h", "crypto/**/*.inl" ]
# # Exclude C AES because we've got the x86_64 one
# exclude = [ "crypto/fipsmodule/aes/aes.c" ]
# include_paths = ["include"]
# fixup_include_paths = ["include"]

# [['cfg(all(target_arch = "x86_64", target_os = "windows"))'.prebuilt_cxx_library]]
# name = "ring-asm-windows-x86_84"
# static_libs = [ "pregenerated/*x86_64*-nasm.obj" ]

# ['cfg(any(all(target_arch = "x86_64", target_os = "windows")))']
# version = "=0.17.5"
# [['cfg(any(all(target_arch = "x86_64", target_os = "windows")))'.prebuilt_cxx_library]]
# name = "ring-asm-windows-x86_84"
# static_libs = [ "pregenerated/*x86_64*-nasm.o" ]
