[package]
name = "query_term_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[dependencies]
query_term.workspace = true
workspace_hack.workspace = true
