[package]
name = "index_error_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils.workspace = true
ffi.workspace = true
index_error.workspace = true
libc.workspace = true
redis-module.workspace = true
workspace_hack.workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[lints]
workspace = true

