[package]
name = "inverted_index_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[dependencies]
ffi.workspace = true
inverted_index.workspace = true
rmp-serde.workspace = true
serde.workspace = true
workspace_hack.workspace = true
