[package]
name = "field"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
workspace_hack.workspace = true

[lints]
workspace = true
