[package]
name = "tracing_redismodule"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
tracing-core.workspace = true
tracing-subscriber.workspace = true
ffi.workspace = true
tracing.workspace = true

[lints]
workspace = true
