[package]
name = "varint"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[lints]
workspace = true

[build-dependencies]
cbindgen.workspace = true

[dependencies]
ffi = { workspace = true }
buffer = { workspace = true }
encode_decode = { workspace = true }

