[package]
name = "rlookup"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
enumflags2.workspace = true
libc.workspace = true
pin-project.workspace = true
sorting_vector.workspace = true
value.workspace = true
strum.workspace = true

[dev-dependencies]
proptest = { workspace = true, features = ["std"] }
value = { workspace = true, features = ["test_utils"] }

[lints]
workspace = true
