[package]
name = "iterators_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ffi.workspace = true
inverted_index.workspace = true
rqe_iterators = { workspace = true, features = ["disable_sort_checks_in_idlist"] }
rqe_iterators_interop.workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }
