[package]
name = "ffi_geiger"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
proc-macro2 = { workspace = true, features = ["span-locations"] }
syn = { workspace = true, features = ["full", "visit"] }
walkdir.workspace = true
workspace_hack.workspace = true

[lints]
workspace = true
