[package]
name = "inverted_index"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
enumflags2.workspace = true
ffi.workspace = true

[lints]
workspace = true
