[package]
name = "inverted_index"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
enumflags2.workspace = true
ffi.workspace = true
field.workspace = true
query_term.workspace = true
thin_vec.workspace = true
qint.workspace = true
redis_reply.workspace = true
smallvec = { workspace = true, features = ["serde", "union"] }
varint.workspace = true
serde.workspace = true
workspace_hack.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
proptest = { workspace = true, features = ["std"] }

[features]
test_utils = []

[lints]
workspace = true
