[package]
name = "value"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils = { workspace = true }
ffi.workspace = true
workspace_hack.workspace = true
thiserror.workspace = true

[dev-dependencies]
redis_mock.workspace = true

[target.'cfg(all(target_env="musl", target_os="linux"))'.dependencies.redis-module]
# Statically link to the libclang on aarch64-unknown-linux-musl,
# necessary on Alpine.
# See https://github.com/rust-lang/rust-bindgen/issues/2360
features = ["bindgen-static", "min-redis-compatibility-version-6-0"]
workspace = true
default-features = false

[target.'cfg(not(all(target_env="musl", target_os="linux")))'.dependencies.redis-module]
workspace = true
default-features = true

[lints]
workspace = true

[features]
# Enables temporary `RSValueFFI` type.
# Needs to be disabled
# in case bindings are being generated for types
# exposed in this crate.
c_ffi_impl = []
