[package]
name = "value"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils = { workspace = true }
ffi = { workspace = true, optional = true }

[target.'cfg(all(target_env="musl", target_os="linux"))'.dependencies.redis-module]
# Statically link to the libclang on aarch64-unknown-linux-musl,
# necessary on Alpine.
# See https://github.com/rust-lang/rust-bindgen/issues/2360
features = ["bindgen-static", "min-redis-compatibility-version-6-0"]
workspace = true
default-features = false

[target.'cfg(not(all(target_env="musl", target_os="linux")))'.dependencies.redis-module]
workspace = true
default-features = true


[lints]
workspace = true

[features]
test_utils = []
# Temporary feature that allows the `RSValueFFI` type
# to use bindings from the `ffi` crate. Needs to be disabled
# in case bindings are being generated for types
# exposed in this crate.
c_ffi_impl = ["dep:ffi"]
