[package]
name = "value"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils = { workspace = true }
ffi.workspace = true
thiserror.workspace = true

[dev-dependencies]
redis_mock.workspace = true


[lints]
workspace = true

[features]
test_utils = []
# Enables temporary `RSValueFFI` type.
# Needs to be disabled
# in case bindings are being generated for types
# exposed in this crate.
c_ffi_impl = []
