[package]
name = "value"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils = { workspace = true }
ffi = { workspace = true, optional = true }
thiserror.workspace = true

[lints]
workspace = true

[features]
test_utils = []
# Temporary feature that allows the `RSValueFFI` type
# to use bindings from the `ffi` crate. Needs to be disabled
# in case bindings are being generated for types
# exposed in this crate.
c_ffi_impl = ["dep:ffi"]
