[package]
name = "document"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
strum.workspace = true
thiserror.workspace = true
workspace_hack.workspace = true

[lints]
workspace = true
