[package]
name = "document_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[dependencies]
c_ffi_utils.workspace = true
libc.workspace = true
document.workspace = true
workspace_hack.workspace = true
