[package]
name = "safety_report"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
syn = { workspace = true, features = ["full", "visit"] }
walkdir.workspace = true
workspace_hack.workspace = true

[lints]
workspace = true
