[package]
name = "redis_reply"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ffi.workspace = true
workspace_hack.workspace = true

[dev-dependencies]
insta.workspace = true
proptest = { workspace = true, features = ["std"] }
redis_mock.workspace = true
