[package]
name = "ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false

[build-dependencies]
cc.workspace = true
build_utils = { path = "../build_utils" }

[target.'cfg(all(target_env="musl", target_os="linux"))'.build-dependencies.bindgen]
# Statically link to the libclang on aarch64-unknown-linux-musl,
# necessary on Alpine.
# See https://github.com/rust-lang/rust-bindgen/issues/2360
features = ["static"]
workspace = true

[target.'cfg(not(all(target_env="musl", target_os="linux")))'.build-dependencies.bindgen]
features = ["runtime"]
workspace = true

[dev-dependencies]
enumflags2.workspace = true

[lints]
workspace = true

[dependencies]
workspace_hack = { version = "0.1", path = "../workspace_hack" }
