[package]
name = "varint"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dev-dependencies]
proptest = { workspace = true, features = ["std"] }
proptest-derive = { workspace = true }

[dependencies]
workspace_hack = { version = "0.1", path = "../workspace_hack" }
