[package]
name = "c_ffi_utils"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
workspace_hack = { version = "0.1", path = "../../workspace_hack" }

[lints]
workspace = true
