[package]
name = "sparse_vector_index_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
# This crate has no Rust unit testsâ€”it only contains bindings.
test = false
bench = false

[dependencies]
sparse_vector_index.workspace = true

[build-dependencies]
build_utils.workspace = true
