[package]
name = "index_error"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils.workspace = true
redis-module.workspace = true
workspace_hack.workspace = true

[lints]
workspace = true

