[package]
name = "iterator_wrapper"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
inverted_index.workspace = true
rqe_iterators.workspace = true

[lints]
workspace = true
