[package]
name = "value_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[dependencies]
c_ffi_utils.workspace = true
ffi.workspace = true
fnv.workspace = true
libc.workspace = true
tracing.workspace = true
value.workspace = true
workspace_hack.workspace = true
