[package]
name = "result_processor"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
pin-project.workspace = true
libc = { workspace = true, features = ["extra_traits"] }
ffi.workspace = true
search_result.workspace = true

[lints]
workspace = true
