[package]
name = "result_processor"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
pin-project.workspace = true
libc = { workspace = true, features = ["extra_traits"] }
ffi.workspace = true
workspace_hack.workspace = true
search_result.workspace = true

[dev-dependencies]
# Crate required to invoke C symbols
result_processor = { path = ".", features = ["unittest"] }
redisearch_rs = { path = "../c_entrypoint/redisearch_rs" }
redis_mock.workspace = true

[build-dependencies]
build_utils.workspace = true

[features]
unittest = []

[lints]
workspace = true
