[package]
name = "search_result"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
inverted_index.workspace = true

enumflags2.workspace = true
unsafe-tools.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }

[lints]
workspace = true
