[package]
name = "search_result"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ffi.workspace = true
inverted_index.workspace = true

enumflags2.workspace = true
unsafe-tools.workspace = true

[lints]
workspace = true
