[package]
name = "module_init_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
tracing_redismodule.workspace = true
tracing = { workspace = true }
ffi.workspace = true
workspace_hack.workspace = true

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[lints]
workspace = true
