[package]
name = "query_error_ffi"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
c_ffi_utils.workspace = true
query_error.workspace = true
workspace_hack = { version = "0.1", path = "../../workspace_hack" }

[build-dependencies]
cbindgen.workspace = true
build_utils = { path = "../../build_utils" }

[lints]
workspace = true
