name: Build on Linux Platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:bullseye"]'

jobs:
  build-linux-matrix:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup
      run: |
        ./sbin/setup
        ./deps/readies/bin/getredis
    - name: Build
      run: |
        make
        make COORD=1
    - name: Unit tests
      run: |
        make unit-tests
    - name: Flow tests
      run: |
        make pytest
    - name: Unit tests (coordinator)
      run: |
        make COORD=1 unit-tests
    - name: Flow tests (coordinator)
      run: |
        make COORD=1 pytest
