name: Build on Linux

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*docs'
      - '*noci'

jobs:
  build-linux-jammy:
    uses: ./.github/workflows/common-flow-host.yml
    with:
      env: ubuntu-22.04
      get-redis: true
    secrets: inherit
