name: Build on macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-12
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: |
        git submodule update --init --recursive
        git config --global --add safe.directory '*'
    - name: Setup
      run: |
        ./sbin/setup
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        ./deps/readies/bin/getredis --with-github-token
    - name: Build
      run: |
        make
        make COORD=1
    - name: Unit tests
      run: |
        make unit-tests
    - name: Flow tests
      run: |
        make pytest QUICK=1
    - name: Unit tests (coordinator)
      run: |
        make COORD=1 unit-tests
    - name: Flow tests (coordinator)
      run: |
        make COORD=1 pytest QUICK=1
