name: Coverage analysis

on:
  push:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        set-safe-directory: "'*'"
    - name: Setup
      run: |
        ./sbin/setup
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        ./deps/readies/bin/getredis --with-github-token
    - name: Build and test
      run: |
        make coverage QUICK=1
