name: Coverage analysis

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  workflow_call:
    inputs:
      rejson:
        type: boolean
        default: true
        description: 'Enable tests with RedisJSON'
      rejson-branch:
        type: string
        default: master
        description: 'Branch to use when building RedisJSON for tests'

env:
  VERBOSE_UTESTS: 1
  REJSON: ${{ inputs.rejson && 1 || 0 }}  # convert the boolean input to numeric
  COV: 1

jobs:
  coverage:
    runs-on: ubuntu-22.04  # Temporary hard coded until we resolve the issues with ubuntu-latest(24)
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # fetch all history for accurate results
    - name: Setup specific
      working-directory: .install
      run: ./install_script.sh sudo
    - name: Setup common
      run: .install/test_deps/common_installations.sh sudo
    - name: Get Redis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./deps/readies/bin/getredis --with-github-token --branch unstable
    - name: Build and test flow
      run: make coverage-flow QUICK=1 SHOW=1 REJSON=${{ env.REJSON }} REJSON_BRANCH=${{ inputs.rejson-branch }}
    - name: Upload flow coverage
      uses: codecov/codecov-action@v5
      with:
        files: bin/linux-x64-debug-cov/flow.info
        disable_search: true
        flags: flow
        fail_ci_if_error: true # Fail on upload errors
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Build and test unit
      run: make coverage-unit QUICK=1 SHOW=1 REJSON=${{ env.REJSON }} REJSON_BRANCH=${{ inputs.rejson-branch }}
    # - name: Upload union coverage
    #   uses: codecov/codecov-action@v5
    #   with:
    #     files: bin/linux-x64-debug-cov/unit.info,bin/linux-x64-debug-cov/rust_cov.info
    #     disable_search: true
    #     flags: unit
    #     fail_ci_if_error: true # Fail on upload errors
    #     token: ${{ secrets.CODECOV_TOKEN }}
