name: Coverage analysis

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  workflow_call:
    inputs:
      rejson:
        type: boolean
        default: true
        description: 'Enable tests with RedisJSON'
      rejson-branch:
        type: string
        default: master
        description: 'Branch to use when building RedisJSON for tests'
      quick:
        type: boolean

env:
  VERBOSE_UTESTS: 1
  REJSON_BRANCH: ${{ inputs.rejson-branch }}
  REJSON: ${{ inputs.rejson && 1 || 0 }}  # convert the boolean input to numeric
  QUICK: ${{ inputs.quick && 1 || 0 }}  # convert the boolean input to numeric
  COV: 1 # make sure the context for any 'make' or script call is for coverage
  RUST_BACKTRACE: "full"

jobs:
  coverage:
    runs-on: ubuntu-22.04  # Temporary hard coded until we resolve the issues with ubuntu-latest(24)
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # fetch all history for accurate results
    - name: Setup specific
      working-directory: .install
      run: ./install_script.sh sudo
    - name: Setup common
      run: .install/test_deps/common_installations.sh sudo

    - name: Get Redis
      uses: actions/checkout@v4
      with:
        repository: redis/redis
        path: redis
    - name: Build Redis
      working-directory: redis
      env:
        REDIS_CFLAGS: -DCOVERAGE_TEST
        BUILD_TLS: yes
      run: make install

    - name: Build
      run: make
    - name: Flow coverage
      run: make coverage-flow
    - name: Unit coverage
      run: make coverage-unit
    - name: Rust coverage
      run: make coverage-rust

    - name: Upload flow coverage
      uses: codecov/codecov-action@v5
      with:
        files: bin/linux-x64-debug-cov/flow.info
        disable_search: true
        flags: flow
        fail_ci_if_error: true # Fail on upload errors
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload unit coverage
      uses: codecov/codecov-action@v5
      with:
        files: bin/linux-x64-debug-cov/unit.info,bin/linux-x64-debug-cov/rust_cov.info
        disable_search: true
        flags: unit
        fail_ci_if_error: true # Fail on upload errors
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload Test Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Test Logs
        path: tests/**/logs/*.log*
        if-no-files-found: ignore
