name: Coverage analysis

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  workflow_call:
    inputs:
      rejson:
        type: boolean
        default: true
        description: 'Enable tests with RedisJSON'
      rejson-branch:
        type: string
        default: master
        description: 'Branch to use when building RedisJSON for tests'

env:
  BOOST_VERSION: ${{ vars.BOOST_VERSION }}
  VERBOSE_UTESTS: 1
  REJSON: ${{ inputs.rejson && 1 || 0 }}  # convert the boolean input to numeric

jobs:
  coverage:
    runs-on: ubuntu-latest
      run:
        shell: bash -l -eo pipefail {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0 # fetch all history for accurate results
    - name: Setup specific
      working-directory: .install
      run: ./install_script.sh sudo
    - name: Setup common
      run: .install/test_deps/common_installations.sh sudo

    - name: Install Boost
      working-directory: .install
      run: ./install_boost.sh ${{ env.BOOST_VERSION }} sudo

    - name: Get Redis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./deps/readies/bin/getredis --with-github-token --branch unstable
    - name: Build and test
      run: make coverage QUICK=1 SHOW=1 REJSON=${{ env.REJSON }} REJSON_BRANCH=${{ inputs.rejson-branch }}
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: bin/linux-x64-debug-cov/cov.info
        disable_search: true
        fail_ci_if_error: true # Fail on upload errors
        token: ${{ secrets.CODECOV_TOKEN }}
