[build]
target-dir = "../../bin/redisearch_rs"

[alias]
license-check = "run --manifest-path tools/license_header_linter/Cargo.toml"
license-fix = "license-check -- --fix"
safety-report = "run --manifest-path tools/safety_report/Cargo.toml"
